export const FETCH_INIT_REQUEST = "movies/FETCH_INIT_REQUEST";
export const FETCH_INIT_FAILED = "movies/FETCH_INIT_FAILED";
export const FETCH_INIT_COMPLETED = "movies/FETCH_INIT_COMPLETED";

export const FETCH_FAVORITES_REQUEST = "movies/FETCH_FAVORITES_REQUEST";
export const FETCH_FAVORITES_FAILED = "movies/FETCH_FAVORITES_FAILED";
export const FETCH_FAVORITES_COMPLETED = "movies/FETCH_FAVORITES_COMPLETED";

export const FILTER_FAVORITES = "movies/FILTER_FAVORITES";
